=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/category.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://arachne.uni-koeln.de/schemas/category"
    targetNamespace="http://arachne.uni-koeln.de/schemas/category"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    <xs:element name="category">        
        <xs:complexType>
            <xs:all>
                <xs:element name="display" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                        	<!-- shouldn't title and subtitle may be only of a single field? -->
                            <xs:element name="title" type="SectionContent" minOccurs="1" maxOccurs="1" />
                            <xs:element name="subtitle" type="SectionContent" minOccurs="1" maxOccurs="1" />
                            <xs:element name="datasections" type="SectionContent" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="facets" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="facet" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="context" type="ContextContent" />
                                        <xs:element name="field" type="FieldContent" />
                                    </xs:choice>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="labelKey" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="hasImage" type="xs:boolean" />
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="SectionContent">
        <xs:choice minOccurs="1" maxOccurs="1">
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="section" type="SectionContent" />
            	<xs:element name="context" type="ContextContent" />
            	<xs:element name="include" type="IncludeContent" />
        	</xs:choice>
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="field" type="FieldContent" />
            	<xs:element name="linkField" type="LinkFieldContent" />
        	</xs:choice>
        </xs:choice>
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="ContextContent">
    	<xs:choice maxOccurs="unbounded">
            <xs:element name="field" type="FieldContent" />
            <xs:element name="linkField" type="LinkFieldContent" />
        </xs:choice>
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="IncludeContent">
    	<xs:attribute name="type" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:complexType name="FieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="field" type="FieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="search" type="xs:string" />
        <xs:attribute name="replace" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="LinkFieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="linkField" type="LinkFieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="labelKey" type="xs:string" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:simpleType name="datasourceString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z\-_]*\.[A-Za-z0-9\-_]+" />
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/gruppen.xml
<?xml version="1.0" encoding="UTF-8"?>

<category name="gruppen"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
        	<section>
            	<field datasource="gruppen.KurzbeschreibungGruppen" />
            </section>
        </title>
        <subtitle>
             <section separator=", ">
                <section separator=" / ">
                    <field datasource="ort.Stadt" />
                    <field datasource="ort.Ort_antik" />
                </section>
                <section>
                	<field datasource="ort.Aufbewahrungsort" />
                </section>
            </section>
        </subtitle>
        <datasections>
        	<section labelKey="Informationen zum mehrteiligen Denkmal (Gruppe)">
        	   <include type="ort" />
        	   <include type="datierung" />
        		<!-- <section labelKey="Datierung">
                    <context type="datierung" labelKey="Gruppenerstaufstellung" separator=" ">
                        <field datasource=".AnfEpoche" postfix="," />
                        <field datasource=".AnfDatZeitraum" />
                        <field datasource=".AnfDatJh" postfix=". Jh."/>
                        <field datasource=".AnfDatvn" />
                    </context>
                    <context type="datierung">
                        <field datasource=".DatVorschlagAutor" prefix="- nach: " postfix=" -"/>
                    </context>
                </section> -->
        		<section labelKey="Allgemein">
        			<!-- Not a nice solution. The first and the last section should not be needed -->
        			<section>
        				<field datasource="gruppen.alternativeBezeichnung" prefix="Alternative Bezeichnung: " />
        				<field datasource="gruppen.ArtDerGruppe" prefix="Art des Denkmals: " />
        			</section>
        			<section separator=", ">
        				<field datasource="gruppen.AnzahlFigurenGruppen" prefix="Anzahl der Figuren/Objekte: " />
        				<field datasource="gruppen.Aufbau" />
        			</section>
        			<section>
        				<field datasource="gruppen.Zusammengehoerigkeit" prefix="Zusammengehörigkeit: " />
        			</section>
        		</section>
        		<section labelKey="Überlieferungen">
        			<field datasource="gruppen.Nachweise"  />
        			<field datasource="gruppen.ArchaeologZeugnisse" />
        			<field datasource="gruppen.AntikeSchriftquellen" />
        		</section>
        		
        		<section labelKey="Aufstellung" separator=", ">
        			<field datasource="gruppen.Aufstellungskontext" />
        			<field datasource="gruppen.FunktionGruppen" />
        			<field datasource="gruppen.AuftraggeberGruppen" />
        			<field datasource="gruppen.AdressatGruppen" />
        		</section>
        		<section labelKey="Herkunft" separator=" ,">
        			<field datasource="gruppen.FundstaatGruppen" />
        			<field datasource="gruppen.FundortGruppen"/>
        			<field datasource="gruppen.FundkontextGruppen" />
        			<field datasource="gruppen.FunddatumGruppen" />
        			<field datasource="gruppen.HerkunftGruppen" />
        			<field datasource="gruppen.HerkFundKommentarGruppen"/>        			
        		</section>
        		<section labelKey="Thematik">
        			<field datasource="gruppen.ThematikGruppen" />
        			<field datasource="gruppen.ThematikMenschen" />
        			<field datasource="gruppen.ZugehoerigeFiguren" prefix="Figuren" />
        			<field datasource="gruppen.ThemaInWorten" />
        		</section>
        		
	            <include type="literatur" />
	            <include type="uri" />
	    	</section>
        </datasections>
    </display>
    <facets>
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="Dataset.TableName" />
    	</facet>
    	<facet name="ort" labelKey="Lokalisierung">
	    	<context type="ort" separator=", ">
		    	<field datasource=".Stadt" />
		    	<field datasource=".Land" />
	    	</context>
    	</facet>
    	<facet name="datierungepoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".AnfEpoche"/>
	    	</context>
    	</facet>
    	<facet name="datierungepoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".EndEpoche"/>
	    	</context>
    	</facet>
    	<facet name="artdergruppe" labelKey="Art der Gruppe">
    		<field datasource="gruppen.ArtDerGruppe" />
    	</facet>     	
    	<facet name="aufbau" labelKey="Aufbau">
    		<field datasource="gruppen.Aufbau" />
    	</facet> 
    	<facet name="aufstellungskontext" labelKey="Aufstellungskontext">
    		<field datasource="gruppen.Aufstellungskontext" />
    	</facet>   
    	<facet name="funktion" labelKey="Funktion">
    		<field datasource="gruppen.FunktionGruppen" />
    	</facet> 
    	<facet name="thematik" labelKey="Thematik">
    		<field datasource="gruppen.ThematikGruppen" />
    	</facet> 
    	<facet name="thematikmenschen" labelKey="Thematik">
    		<field datasource="gruppen.ThematikMenschen" />
    	</facet>
    	<facet name="archaeologzeugnisse" labelKey="Archäologische Zeugnisse">
    		<field datasource="gruppen.ArchaeologZeugnisse" />
    	</facet> 
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/quantities.xml
<?xml version="1.0" encoding="UTF-8"?>
<category name="quantities" xmlns="http://arachne.uni-koeln.de/schemas/category"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
            <section separator=" / ">
                <field datasource="morphology.Level6">
                    <ifEmpty>
                        <field datasource="morphology.Level5">
                            <ifEmpty>
                                <field datasource="morphology.Level4">
                                    <ifEmpty>
                                        <field datasource="morphology.Level3">
                                            <ifEmpty>
                                                <field datasource="morphology.Level2">
                                                    <ifEmpty>
                                                        <field datasource="morphology.Level1"/>
                                                    </ifEmpty>
                                                </field>
                                            </ifEmpty>
                                        </field>
                                    </ifEmpty>
                                </field>
                            </ifEmpty>
                        </field>
                    </ifEmpty>
                </field>
                <field datasource="befund.Grabungsort"/>
                <field datasource="fabric.CommonName"/>
            </section>
        </title>
        <subtitle>
            <section labelKey="Quantity">
                <field datasource="Dataset.Id" />
            </section>
        </subtitle>

        <datasections>
            <section labelKey="Informationen zur Quantity">
                <field datasource="quantities.RimCount"/>
                <field datasource="quantities.RimWeight" postfix="g"/>
                <field datasource="quantities.RimPercentage" postfix="%"/>
                <field datasource="quantities.HandleCount"/>
                <field datasource="quantities.HandleWeight" postfix="g"/>
                <field datasource="quantities.BaseCount"/>
                <field datasource="quantities.BaseWeight" postfix="g"/>
                <field datasource="quantities.BodySherdCount"/>
                <field datasource="quantities.BodySherdWeight" postfix="g"/>
                <field datasource="quantities.OthersCount"/>
                <field datasource="quantities.OthersWeight" postfix="g"/>
                <field datasource="quantities.Joins"/>
                <field datasource="quantities.MNI"/>
                <field datasource="quantities.MNIWeighted"/>
                <field datasource="quantities.MXI"/>
            </section>
        </datasections>
    </display>
    <facets>
        <facet name="kategorie" labelKey="Kategorie">
            <field datasource="Dataset.TableName"/>
        </facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/ort.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- just very basic to have at least some definitions -->
<category name="ort"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
        	<section separator=", ">
        		<field datasource="ort.Stadt" />
        		<field datasource="ort.Ort_antik" prefix="(" postfix=") " />
        		<field datasource="ort.Land" />
        		<field datasource="ort.Aufbewahrungsort" />
            </section>
        </title>
        <subtitle>
            <section separator=", ">
            	<field datasource="ort.continent" />
            </section>
        </subtitle>
        <datasections>
        	<section labelKey="Informationen zum Ort">
        		<section labelKey="Koordinaten">
	            	<field datasource="ort.Longitude" prefix="Long: " />
	            	<field datasource="ort.Latitude" prefix="Lat: " />
	            	<field datasource="ort.Genauigkeit" />
	            	<field datasource="ort.Aufbewahrungsort"/>
	            </section>
	            
        		<section labelKey="LÃ¤ndercode">
	            	<field datasource="ort.Countrycode" />	            	
	            </section>
	            <section labelKey="Kontinentcode">
	            	<field datasource="ort.continentCode" />
	            </section>
	            <section labelKey="GeonamesID">
	            	<field datasource="ort.Geonamesid" />
	            </section>
        	</section>
        </datasections>
    </display>
    <facets>
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="Dataset.TableName" />
    	</facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/surfacetreatmentaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<category name="surfacetreatmentaction" xmlns="http://arachne.uni-koeln.de/schemas/category"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
            <section separator=" / ">
                <context type="surfacetreatment" separator=" ">
                    <field datasource=".Bezeichner"/>
                </context>
            </section>
        </title>
        <subtitle>
            <section separator=" / ">
                <field datasource="surfacetreatmentaction.TreatmentAction"/>
                <field datasource="surfacetreatmentaction.TreatmentPosition"/>           
            </section>
        </subtitle>
        
        <datasections>
            <section labelKey="Informationen zur Oberflächenbehandlung">
                <field datasource="surfacetreatmentaction.MomentOfSurfaceTreatmentAction"/>
                <field datasource="surfacetreatmentaction.TreatmentPosition"/> 
                <field datasource="surfacetreatmentaction.PartOfSurfaceTreated"/>
                <field datasource="surfacetreatmentaction.Condition"/>
                <field datasource="surfacetreatmentaction.NumberOfSherds"/> 
            </section>
            <section labelKey="Informationen zur Behandlungstechnik">
                <field datasource="surfacetreatmentaction.TreatmentAction"/>
                <field datasource="surfacetreatmentaction.TreatmentActionSubCoating"/> 
                <field datasource="surfacetreatmentaction.IncisionDescription"/>
                <field datasource="surfacetreatmentaction.StampedStamp"/> 
                <field datasource="surfacetreatmentaction.AddedMaterialType"/> 
            </section>
            <section labelKey="Beschreibung der Oberflächenbehandlung">
                <field datasource="surfacetreatmentaction.Thickness"/>
                <field datasource="surfacetreatmentaction.Glossiness"/> 
                <field datasource="surfacetreatmentaction.Conservation"/>
                <field datasource="surfacetreatmentaction.Quality"/> 
                <field datasource="surfacetreatmentaction.Homogenity"/> 
                <field datasource="surfacetreatmentaction.Adherence"/> 
                <field datasource="surfacetreatmentaction.Alignment"/> 
                <field datasource="surfacetreatmentaction.FreeDescription"/> 
            </section>
            <section labelKey="Farbinformationen">
                <field datasource="surfacetreatmentaction.ColourFreeQualifierVon"/>
                <field datasource="surfacetreatmentaction.ColourFreeVon"/> 
                <field datasource="surfacetreatmentaction.ColourFreeQualifierBis"/>
                <field datasource="surfacetreatmentaction.ColourFreeBis"/> 
                <field datasource="surfacetreatmentaction.ColourMunsellVon"/> 
                <field datasource="surfacetreatmentaction.ColourMunsellBis"/> 
            </section>
           </datasections>
    </display>
    <facets>
        <facet name="kategorie" labelKey="Kategorie">
            <field datasource="Dataset.TableName" />
        </facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/befund.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  CeramEgypt Objects 2.0
  a befund object (where a piece of ceramics was found)
-->
<category xmlns="http://arachne.uni-koeln.de/schemas/category" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="befund" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
  <display>
    <title>
      <section separator=" / ">
        <field datasource="befund.Grabungsort"/>
        <field datasource="befund.Areal" />
        <field datasource="befund.Befund" />
      </section>
    </title>
    <subtitle labelKey="">
      <section labelKey="Unique Identifier">
        <field datasource="Dataset.internalId"/>
      </section>
    </subtitle>
    <datasections>
      <include type="befund" />
      <include type="datierung"/>
    </datasections>

    <contextImages>
    </contextImages>
  </display>
  <facets>

    <include type="facet_kategorie"/>

    <include type="facet_ort"/>

    <include type="facet_befund" />

  </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/individualvessel.xml
<?xml version="1.0" encoding="UTF-8"?>
<category name="individualvessel" xmlns="http://arachne.uni-koeln.de/schemas/category"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
            <section separator=" / ">
                <field datasource="individualvessel.InventoryNumber"/>
            </section>
        </title>
        <subtitle>
            <section labelKey="Individual Vessel">
                <field datasource="Dataset.Id"/>
            </section>
        </subtitle>
        <datasections>
            <section labelKey="Quantifizierung des Gefäßes">
                <section labelKey="Anzahl Randfragmente">
                    <field datasource="individualvessel.RimCount"/>
                </section>
                <section labelKey="Anzahl Henkel">
                    <field datasource="individualvessel.HanldeCount"/>
                </section>
                <section labelKey="Anzahl Bodenfragmente">
                    <field datasource="individualvessel.BaseCount"/>
                </section>
                <section labelKey="Anzahl Wandfragmente">
                    <field datasource="individualvessel.BodySherdCount"/>
                </section>
                <section labelKey="Anzahl weiterer Fragmente">
                    <field datasource="individualvessel.OthersCount"/>
                </section>
                <section labelKey="Anzahl Joins">
                    <field datasource="individualvessel.Joins"/>
                </section>
                <section labelKey="Prozentualer Randanteil">
                    <field datasource="individualvessel.RimPercentage" postfix="%"/>
                </section>
            </section>
            <section labelKey="Maße des Gefäßes">
                <section labelKey="Höhe">
                    <field datasource="individualvessel.Height" postfix="cm"/>
                </section>
                <section labelKey="Breite">
                    <field datasource="individualvessel.Width" postfix="cm"/>
                </section>
                <section labelKey="Länge">
                    <field datasource="individualvessel.LengthSize" postfix="cm"/>
                </section>
                <section labelKey="Dicke">
                    <field datasource="individualvessel.Thickness" postfix="cm"/>
                </section>
                <section labelKey="Bodendurchmesser">
                    <field datasource="individualvessel.BaseDiameter" postfix="cm"/>
                </section>
                <section labelKey="Randdurchmesser">
                    <field datasource="individualvessel.RimDiameter" postfix="cm"/>
                </section>
                <section labelKey="Durchmesser der breitesten Stelle">
                    <field datasource="individualvessel.WidestDiameter" postfix="cm"/>
                </section>
                <section labelKey="Volumen">
                    <field datasource="individualvessel.Volume" postfix="cm³"/>
                </section>
            </section>
        </datasections>
    </display>
    <facets>
        <facet name="kategorie" labelKey="Kategorie">
            <field datasource="Dataset.TableName" />
        </facet>
        <facet name="vessel-inventorynumber" labelKey="Inventarnummer">
            <field datasource="individualvessel.InventoryNumber" />
        </facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/realien.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- not sure how to really handle this, so it is far from complete -->
<category name="realien"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
        	<section>
            	<field datasource="realien.KurzbeschreibungRealien" />
            </section>
        </title>
        <subtitle>
             <section separator=", ">
                <section separator=" / ">
                    <field datasource="ort.Stadt" />
                    <field datasource="ort.Ort_antik" />
                </section>
                <field datasource="ort.Aufbewahrungsort" />
            </section>
        </subtitle>
        <datasections>
        	<section labelKey="Informationen">
        		<section labelKey="Bildkontext">
        			<field datasource="realien.Lokalisierung" prefix="Lokalisierung: " />
        		</section>
        		<section labelKey="Erhaltung und Ãœberarbeitung">
        			<section separator=", ">
        				<field datasource="realien.ErhaltungRealien" prefix="Erhaltungszustand: " />
        				<field datasource="realien.ErhaltungszustandRealien" />
        			</section>
        			<section>
        				<field datasource="realien.BearbeitungenRealien" prefix="Bearbeitungen: " />
        			</section>
        			<section>
        				<field datasource="realien.BearbeitungenModernRealien" prefix="modern: " />
        			</section>
        		</section>
        		<section labelKey="Figur">
        			<section>
        				<field datasource="realien.WesenRealien" prefix="Wesen: " />
        			</section>
        			<section separator=", ">
        				<field datasource="realien.BenennungAllgRealien" prefix="Benennung: " />
        				<field datasource="realien.BenennungSpez" />
        			</section>
        			<section>
        				<field datasource="realien.GeschlechtRealien" />
        			</section>
        			<section>
        				<field datasource="realien.LebensalterRealien" prefix="Lebensalter: "/>
        			</section>
        		</section>
        		<section labelKey="Haltung">
        			<field datasource="realien.HaltungRealien" prefix="Haltung: " />
        			<field datasource="realien.Richtung" />        		
        		</section>
        		<section labelKey="Bekleidung">
        			<section>
        				<field datasource="realien.bekleidetRealien" />
        			</section>
        			<section separator=", ">
        				<field datasource="realien.KleidungAllg" prefix="Kleidung: " />
        				<field datasource="realien.KleidungSpez" />
        			</section>        		
        		</section>
        		<section labelKey="Haartracht">
        			<section separator=", ">
        				<field datasource="realien.HaartrachtAllg" prefix="Haartracht: " />
        				<field datasource="realien.HaartrachtSpez" />
        			</section>
        			<section separator=", ">
        				<field datasource="realien.KopfbedeckungAllg" prefix="Kopfbedeckung: " />
        				<field datasource="realien.KopfbedeckungSpez" />
        			</section>	        		
        		</section>
        		<!-- unfortunately realien seem not to be connected to a context so this does not work
        		<section labelKey="Aufbewahrung">
        			<context type="ort" separator=", ">
        				<field datasource=".Stadt"  />
        				<field datasource=".Land" />
        				<field datasource=".Countrycode" />
        				<field datasource=".Aufbewahrungsort" />
        			</context>
        		</section>
        		<section labelKey="Datierung">
	            	<context type="datierung" separator=" ">
	            		<field datasource=".AnfEpoche" postfix="," />
	            		<field datasource=".AnfDatZeitraum" />
	            		<field datasource=".AnfDatJh" postfix=". Jh."/>
	            		<field datasource=".AnfDatvn" />
	            	</context>
	            	<context type="datierung">
	            		<field datasource=".DatVorschlagAutor" prefix="- nach: " postfix=" -"/>
	            	</context>
	            </section>
        		<context type="literatur" labelKey="Literatur" separator=" ">
	            	<field datasource=".tempLiteratur" />
	            	<field datasource=".DAIRichtlinien" />
	            	<field datasource=".Seite" />
	            </context>
	            -->
	    	</section>
        </datasections>
    </display>
    <facets>
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="Dataset.TableName" />
    	</facet>
    	<facet name="ort" labelKey="Lokalisierung">
	    	<context type="ort" separator=", ">
		    	<field datasource=".Stadt" />
		    	<field datasource=".Land" />
	    	</context>
    	</facet>
    	<facet name="datierung-epoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".AnfEpoche"/>
	    	</context>
    	</facet>
    	<facet name="datierung-epoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".EndEpoche"/>
	    	</context>
    	</facet>
    </facets>
</category>
