=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/category.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://arachne.uni-koeln.de/schemas/category"
    targetNamespace="http://arachne.uni-koeln.de/schemas/category"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    <xs:element name="category">        
        <xs:complexType>
            <xs:all>
                <xs:element name="display" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                        	<!-- shouldn't title and subtitle may be only of a single field? -->
                            <xs:element name="title" type="SectionContent" minOccurs="1" maxOccurs="1" />
                            <xs:element name="subtitle" type="SectionContent" minOccurs="1" maxOccurs="1" />
                            <xs:element name="datasections" type="SectionContent" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="facets" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="facet" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="context" type="ContextContent" />
                                        <xs:element name="field" type="FieldContent" />
                                    </xs:choice>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="labelKey" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="hasImage" type="xs:boolean" />
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="SectionContent">
        <xs:choice minOccurs="1" maxOccurs="1">
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="section" type="SectionContent" />
            	<xs:element name="context" type="ContextContent" />
            	<xs:element name="include" type="IncludeContent" />
        	</xs:choice>
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="field" type="FieldContent" />
            	<xs:element name="linkField" type="LinkFieldContent" />
        	</xs:choice>
        </xs:choice>
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="ContextContent">
    	<xs:choice maxOccurs="unbounded">
            <xs:element name="field" type="FieldContent" />
            <xs:element name="linkField" type="LinkFieldContent" />
        </xs:choice>
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="IncludeContent">
    	<xs:attribute name="type" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:complexType name="FieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="field" type="FieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="search" type="xs:string" />
        <xs:attribute name="replace" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="LinkFieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="linkField" type="LinkFieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="labelKey" type="xs:string" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:simpleType name="datasourceString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z\-_]*\.[A-Za-z0-9\-_]+" />
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/marbilder.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- just very basic to have at least some definitions -->
<category name="bilder"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
        	<section>
            	<field datasource="marbilder.DateinameMarbilder" />
            </section>
        </title>
        <subtitle>
             <section>
                <field datasource="marbilder.Scannummer" />
            </section>
        </subtitle>
        <datasections>
        	<section labelKey="Informationen zum Bild">
        		<section labelKey="Allgemein">
        			<field datasource="marbilder.DateinameMarbilder" prefix="Dateiname: " />
        			<field datasource="marbilder.Dateiformat" prefix="Dateiformat: " />
        			<field datasource="marbilder.Dateigroesse" prefix="Dateigröße: " postfix=" kb" />
        			<field datasource="marbilder.AnzahlFigurenGruppen" prefix="Pfad: " />
        			<field datasource="marbilder.Scannummer" prefix="Scannummer: " />
        			<field datasource="marbilder.erstellt" prefix="Erstellt: " />
        			<field datasource="marbilder.geaendert" prefix="Geändert: " />
        		</section>
        	</section>
        </datasections>
    </display>
    <facets>
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="Dataset.TableName" />
    	</facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/surfacetreatment.xml
<?xml version="1.0" encoding="UTF-8"?>
<category name="surfacetreatment" xmlns="http://arachne.uni-koeln.de/schemas/category"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
            <section>
                <field datasource="surfacetreatment.Bezeichner"/>
            </section>
        </title>
        <subtitle>
            <section labelKey="Surfacetreatment">
                <field datasource="Dataset.Id"/>
            </section>
        </subtitle>

        <datasections>
            <section labelKey="Surfacetreatment Actions">
                <context type="surfacetreatmentaction" labelKey="Oberflächenbehandlungen"
                    separator=" ">
                    <field datasource=".MomentOfSurfaceTreatmentAction"/>
                    <field datasource=".TreatmentPosition"/>
                    <field datasource=".PartOfSurfaceTreated"/>
                    <field datasource=".Condition"/>
                    <field datasource=".NumberOfSherds"/>

                    <field datasource=".TreatmentAction"/>
                    <field datasource=".TreatmentActionSubCoating"/>
                    <field datasource=".IncisionDescription"/>
                    <field datasource=".StampedStamp"/>
                    <field datasource=".AddedMaterialType"/>
                </context>
            </section>
        </datasections>
    </display>
    <facets>
        <facet name="kategorie" labelKey="Kategorie">
            <field datasource="Dataset.TableName"/>
        </facet>
        <facet name="surfacetreatment-bezeichner" labelKey="Bezeichner">
            <field datasource="surfacetreatment.Bezeichner"/>
        </facet>
        <facet name="surfacetreatmentaction-action" labelKey="Art der Oberflächenbehandlung">
            <context type="surfacetreatmentaction">
                <field datasource=".TreatmentAction"/>
            </context>
        </facet>
        <facet name="surfacetreatmentaction-position" labelKey="Position der Oberflächenbehandlung">
            <context type="surfacetreatmentaction">
                <field datasource=".TreatmentPosition"/>
            </context>
        </facet>
        <facet name="surfacetreatmentaction-moment" labelKey="Zeitpunkt der Oberflächenbehandlung">
            <context type="surfacetreatmentaction">
                <field datasource=".MomentOfSurfaceTreatmentAction"/>
            </context>
        </facet>
        <facet name="surfacetreatmentaction-partofsurfacetreatet" labelKey="Behandelter Teil der Oberfläche">
            <context type="surfacetreatmentaction">
                <field datasource=".PartOfSurfaceTreated"/>
            </context>
        </facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/fabricdescription.xml
<?xml version="1.0" encoding="UTF-8"?>
<category xmlns="http://arachne.uni-koeln.de/schemas/category" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="fabricdescription" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
  <display>
    <title>
      <section separator=", ">
        <field datasource="fabric.origin"/>
        <field datasource="fabric.CommonName"/>
        <field datasource="fabric.Name"/>
      </section>
    </title>
    <subtitle>
      <section labelKey="Fabricdescription">
        <field datasource="Dataset.Id"/>
      </section>
    </subtitle>
    <datasections>
      <section labelKey="Informationen zur Fabricdescription">
        <section labelKey="Informationen zur Bruchstelle">
          <section labelKey="Freie Farbbeschreibung" separator=" ">
            <field datasource="fabricdescription.ColourOfBreakQualifierVon"/>
            <field datasource="fabricdescription.ColourOfBreakVon" postfix=" - "/>
            <field datasource="fabricdescription.ColourOfBreakQualifierBis"/>
            <field datasource="fabricdescription.ColourOfBreakBis"/>
          </section>
          <section labelKey="Farbbeschreibung nach Munsell">
            <field datasource="fabricdescription.ColourOfBreakMunsellVon" postfix=" - "/>
            <field datasource="fabricdescription.ColourOfBreakMunsellBis"/>
          </section>
          <section labelKey="Zoning">
            <field datasource="fabricdescription.Zoning"/>
          </section>
        </section>
        <section labelKey="Informationen zum Kern">
          <section labelKey="Freie Farbbeschreibung" separator=" ">
            <field datasource="fabricdescription.ColourOfCoreQualifierVon"/>
            <field datasource="fabricdescription.ColourOfCoreVon" postfix=" - "/>
            <field datasource="fabricdescription.ColourOfCoreQualifierBis"/>
            <field datasource="fabricdescription.ColourOfCoreBis"/>
          </section>
          <section labelKey="Farbbeschreibung nach Munsell" separator=" - ">
            <field datasource="fabricdescription.ColourOfCoreMunsellVon"/>
            <field datasource="fabricdescription.ColourOfCoreMunsellBis"/>
          </section>
        </section>
        <section labelKey="Informationen zur Außenhülle">
          <section labelKey="Freie Farbbeschreibung" separator=" ">
            <field datasource="fabricdescription.ColourOfOutsideQualifierVon"/>
            <field datasource="fabricdescription.ColourOfOutsideVon" postfix=" - "/>
            <field datasource="fabricdescription.ColourOfOutsideQualifierBis"/>
            <field datasource="fabricdescription.ColourOfOutsideBis"/>
          </section>
          <section labelKey="Farbbeschreibung nach Munsell" separator=" - ">
            <field datasource="fabricdescription.ColourOfOutsideMunsellVon"/>
            <field datasource="fabricdescription.ColourOfOutsideMunsellBis"/>
          </section>
        </section>
        <section labelKey="Informationen zur Struktur">
          <section labelKey="Fabrikation">
            <field datasource="fabricdescription.Manufacture"/>
          </section>
          <section labelKey="Härte">
            <field datasource="fabricdescription.Hardness"/>
          </section>
          <section labelKey="Bruch">
            <field datasource="fabricdescription.Fracture"/>
          </section>
          <section labelKey="Porösität">
            <field datasource="fabricdescription.Porosity"/>
          </section>
          <section labelKey="Kommentar">
            <field datasource="fabricdescription.Comments"/>
          </section>
        </section>
        <section labelKey="Informationen zur Oberfläche">
          <section labelKey="Oberflächengefühl">
            <field datasource="fabricdescription.SurfaceFeel"/>
          </section>
          <section labelKey="Freie Farbbeschreibung" separator=" ">
            <field datasource="fabricdescription.ColourQualifierFreeVon"/>
            <field datasource="fabricdescription.ColourFreeVon" postfix=" - "/>
            <field datasource="fabricdescription.ColourQualifierFreeBis"/>
            <field datasource="fabricdescription.ColourFreeBis"/>
          </section>
          <section labelKey="Farbbeschreibung nach Munsell" separator=" - ">
            <field datasource="fabricdescription.ColourMunsellVon" postfix=" - "/>
            <field datasource="fabricdescription.ColourMunsellBis"/>
          </section>
        </section>
        <context type="einschluss" labelKey="Einschlüsse" separator=" ">
          <contextSection labelKey="Einschlussart">
            <field datasource=".Einschlussart"/>
          </contextSection>
          <contextSection labelKey="Häufigkeit">
            <field datasource=".Haeufigkeit"/>
          </contextSection>
          <contextSection labelKey="Durchschnittliche Größe">
            <field datasource=".DurchschnittlicheGroesse"/>
          </contextSection>
          <contextSection labelKey="Verteilung">
            <field datasource=".Verteilung"/>
          </contextSection>
        </context>
        <include type="datierung"/>
        <include type="ort"/>
      </section>
    </datasections>
  </display>
  <facets>
    <include type="facet_kategorie"/>
    <include type="facet_ort"/>
    <facet name="datierungepoche" labelKey="Epoche">
      <context type="datierung">
        <field datasource=".AnfEpoche"/>
      </context>
    </facet>
    <facet name="datierungepoche" labelKey="Epoche">
      <context type="datierung">
        <field datasource=".EndEpoche"/>
      </context>
    </facet>
    <!-- Facet-Inclusion -->
    <facet name="einschlusstyp" labelKey="Art des Einschlusses">
      <context type="einschluss">
        <field datasource=".Einschlussart"/>
      </context>
    </facet>
    <facet name="einschlussform" labelKey="Form des Einschlusses">
      <context type="einschluss">
        <field datasource=".Form"/>
      </context>
    </facet>
  </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/buch.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- just very basic to have at least some definitions -->
<category name="buch"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
        	<section>
        		<field datasource="buch.BuchTitel">
                    <ifEmpty>
                    	<field datasource="buch.KurzbeschreibungBuch" />
                	</ifEmpty> 
                </field>
            </section>
        </title>
        <subtitle>
            <section>
            	<field datasource="buch.alias" />
            </section>
        </subtitle>
        <datasections>
        	<section labelKey="Informationen zum Buch">
        		<section labelKey="" prefix="Erscheinungsdatum">
	            	<field datasource="buch.PubYearStart" prefix="frühestes geschätztes Publikationsjahr: " />
	            	<field datasource="buch.PubYearEnd" prefix="spätestes geschätztes Publikationsjahr: " />
	            </section>
	            <section labelKey="Autor">
	            	<field datasource="buch.BuchAutor" />
	            </section>
	            <section labelKey="Physische Beschreibung">
	            	<field datasource="buch.BuchSeiten" prefix="Seiten: "/>
	               	<field datasource="buch.HoeheGesamt" prefix="Höhe: " />
	            	<field datasource="buch.BreiteGesamt" prefix="Breite: " />
	            	<field datasource="buch.TiefeGesamt" prefix="Tiefe: " />
	            </section>
	            <context type="ort" labelKey="Lokalisierung" separator=", ">
	            	<field datasource=".Stadt"  />
        			<field datasource=".Land" />
        			<field datasource=".Countrycode" />
        			<field datasource=".Aufbewahrungsort" />
	            </context>
	            <section labelKey="BibId">
	            	<field datasource="buch.bibid" />
	            </section>
        	</section>
        </datasections>
    </display>
    <facets>
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="Dataset.TableName" />
    	</facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/modell3d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- just very basic to have at least some definitions -->
<category xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="modell3d"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
	<display>
		<title>
			<section>
				<field datasource="modell3d.Titel" />
			</section>
		</title>
		<subtitle>
			<section>
				<field datasource="modell3d.Dateiname" />
			</section>
		</subtitle>
		<datasections>
			<section labelKey="Informationen zum Modell">
				<section labelKey="Allgemein">
					<field datasource="modell3d.Dateiname" prefix="Dateiname: " />
					<field datasource="modell3d.Dateiformat" prefix="Dateiformat: " />
					<field datasource="modell3d.DateinameMTL" prefix="Dateiname (Material): " />
				</section>
				<section labelKey="Angaben zum Modell">
					<field datasource="modell3d.Modellierer" prefix="Modellierer: " />
					<field datasource="modell3d.Lizenz" prefix="Lizenz: " />
				</section>
			</section>
		</datasections>
		<editorsection>
			<section labelKey="Für Bearbeiter">
				<field datasource="modell3d.DatensatzGruppeModell3d" prefix="Datensatz-Gruppe: " />
				<field datasource="modell3d.Pfad" prefix="Pfad: " />
			</section>
		</editorsection>
	</display>
	<facets>
		<include type="facet_kategorie" />
	</facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/topographie.xml
<?xml version="1.0" encoding="UTF-8"?>
<category xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="topographie"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
	<display>
		<title>
			<section>
				<field datasource="topographie.KurzbeschreibungTopographie" />
			</section>
		</title>
		<subtitle>
			<section separator=", ">
				<section>
					<field datasource="topographie.modernerOrt">
						<ifEmpty>
							<field datasource="ort.Stadt" />
						</ifEmpty>
					</field>
					<field datasource="topographie.antikerOrt" prefix="(" postfix=")">
						<ifEmpty>
							<field datasource="ort.Ort_antik" prefix="(" postfix=")" />
						</ifEmpty>
					</field>
				</section>
				<field datasource="ort.Land" />
			</section>
		</subtitle>
		<datasections>
			<section labelKey="Informationen zur Topographie">
				<include type="ort" />
				<include type="datierung" />
				<section labelKey="Beschreibung">
					<field datasource="topographie.TopographieArt" />
					<field datasource="topographie.TopographieTypus" prefix="Kategorie: " />
					<field datasource="topographie.TopographieTypusZusatz"
						prefix="Zusatz: " />
					<field datasource="topographie.antikeGriechLandschaftTopographie"
						prefix="Antike Landschaft: " />
					<field datasource="topographie.antikeRoemProvinzTopographie"
						prefix="Römische Provinz: " />
					<field datasource="topographie.Ausdehnung" prefix="Ausdehnung: " />
					<field datasource="topographie.antikeQuellen" prefix="antike Quellen: " />
					<field datasource="topographie.freieBeschreibung" prefix="Freie Beschreibung: " />
					<field datasource="topographie.KommentarTopographie" prefix="Kommentar: " />
				</section>
				<section labelKey="Geschichte">
					<field datasource="topographie.GeschichteTopographie" />
				</section>
				<section labelKey="Ausgrabungen">
					<field datasource="topographie.Ausgrabungen" />
				</section>
				<include type="literaturcomplete" />
				<include type="uri" />
			</section>
		</datasections>
		<editorsection>
			<section labelKey="Für Bearbeiter">
				<field datasource="topographie.DatensatzGruppeTopographie" prefix="Datensatz-Gruppe: " />
				<field datasource="topographie.ArbeitsnotizTopographie" prefix="Interne Arbeitsnotiz: " />
				<field datasource="topographie.BearbeiterTopographie" prefix="Erstellt von: " />
				<field datasource="topographie.KorrektorTopographie" prefix="Bearbeitet von: " />
			</section>
		</editorsection>
	</display>
	<facets>
		<include type="facet_kategorie" />
		<include type="facet_ort" />
		<include type="facet_datierung" />
		<include type="facet_literatur" />
		<facet name="topographieart" labelKey="Natürlich oder Anthropogen">
			<field datasource="topographie.TopographieArt" />
		</facet>
		<facet name="topographietypus" labelKey="Art der Topographie">
			<field datasource="topographie.TopographieTypus" />
		</facet>
		<facet name="antikegriechlandschaft" labelKey="Antike Landschaft">
			<field datasource="topographie.antikeGriechLandschaftTopographie" />
		</facet>
		<facet name="regioromitalien" labelKey="Regio Rom/Italien">
			<field datasource="topographie.RegioRomItalienTopographie" />
		</facet>
		<facet name="antikeroemprovinz" labelKey="Römische Provinz">
			<field datasource="topographie.antikeRoemProvinzTopographie" />
		</facet>
	</facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/sarkophag.xml
<?xml version="1.0" encoding="UTF-8"?>

<category name="sarkophag"
    xmlns="http://arachne.uni-koeln.de/schemas/category"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
	<display>
		<title>
			<section>
				<field datasource="sarkophag.KurzbeschreibungSarkophag" />
			</section>
		</title>
		<subtitle>
			<section>
				<field datasource="sarkophag.KurzbeschreibungSarkophag" />
			</section>
		</subtitle>
		<datasections>
			<section labelKey="Informationen zum Sarkophag">
				<section labelKey="Herkunft">
					<section separator=", ">
						<field datasource="sarkophag.Fundstaat" />
						<field datasource="sarkophag.Fundort" />
						<field datasource="sarkophag.Fundkontext" />
					</section>
					<context type="objekt" separator=", ">
						<field datasource=".FunddatumObjekt" />
						<field datasource=".Herkunft" />
						<field datasource=".HerkFundKommentar" />
					</context>
				</section>
				<section labelKey="Thematik">
					<section labelKey="Allgemein">
						<field datasource="sarkophag.Thematik" />
						<field datasource="sarkophag.ThematikFrei" />
					</section>
					<section labelKey="Deckel">
						<field datasource="sarkophag.ThematikDeckel" prefix="Thematik: " />
						<field datasource="sarkophag.ThematikDeckelVorderseite" prefix="Hauptthema: " />
						<field datasource="sarkophag.ThematikDeckelNebenseiten" prefix="Nebenthema: " />
					</section>
					<section labelKey="Kasten">
						<field datasource="sarkophag.ThematikKasten" prefix="Thematik: " />
						<field datasource="sarkophag.ThematikKastenVorderseite" prefix="Hauptthema: " />
						<field datasource="sarkophag.ThematikKastenNebenseiten" prefix="Nebenthema: " />
					</section>
				</section>
				<section labelKey="Dekoration">
					<field datasource="sarkophag.Dekoration" />
				</section>
				<section labelKey="Material">
					<field datasource="sarkophag.Material" />
				</section>
			</section>
		</datasections>
	</display>
	<facets>
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="Dataset.TableName" />
    	</facet>
    	<facet name="ort" labelKey="Lokalisierung">
    		<field datasource="Dataset.TableName" />
    	</facet>
	</facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/objekt.xml
<?xml version="1.0" encoding="UTF-8"?>

<category name="objekt"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
        	<section>
            	<field datasource="objekt.KurzbeschreibungObjekt" />
            </section>
        </title>
        <subtitle>
             <section separator=", ">
                <section separator=" / ">
                    <field datasource="ort.Stadt" />
                    <field datasource="ort.Ort_antik" />
                </section>
                <field datasource="ort.Aufbewahrungsort" />
            </section>
        </subtitle>
        <datasections>
        	<section labelKey="Informationen zum Objekt">
        		<section labelKey="Lokalisierung">
        			<context type="ort" separator=", ">
        				<field datasource=".Stadt"  />
        				<field datasource=".Land" />
        				<field datasource=".Countrycode" />
        				<field datasource=".Aufbewahrungsort" />
        			</context>
        		</section>
        		<section labelKey="Herkunft">
        			<field datasource="objekt.HerkFundKommentar" />
        		</section>
        		<section labelKey="Gattung/Funktion/Kulturepoche">
        			<field datasource="objekt.GattungAllgemein" />
        			<field datasource="objekt.Funktion" />
        			<field datasource="objekt.zuMonument" prefix="zu Monument gehörig: " />
        			<field datasource="objekt.Kulturkreis" prefix="Kulturepoche: " />
        		</section>
        		<context type="datierung" labelKey="Datierung" separator=" ">
	            	<field datasource=".AnfEpoche" postfix="," />
	            	<field datasource=".AnfDatZeitraum" />
	            	<field datasource=".AnfDatJh" postfix=". Jh."/>
	            	<field datasource=".AnfDatvn" />
	            </context>
	            <section labelKey="Technik">
	            	<field datasource="objekt.Technik" />
	            </section>
	            <section labelKey="Material">
	            	<field datasource="objekt.Material" />
	            	<field datasource="objekt.Materialbeschreibung" />
	            </section>
	            <section labelKey="Maße">
	            	<field datasource="objekt.BreiteGesamt" prefix="Breite: " postfix=" cm" />
	            	<field datasource="objekt.HoeheGesamt" prefix="Höhe: " postfix=" cm" />
	            	<field datasource="objekt.TiefeGesamt" prefix="Tiefe: " postfix=" cm" />
	            </section>
	            <context type="literatur" labelKey="Literatur" separator=" ">
	            	<field datasource=".tempLiteratur" />
	            	<field datasource=".DAIRichtlinien" />
	            	<field datasource=".Seite" />
	            </context>
	    	</section>
        </datasections>
    </display>
    <facets>
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="Dataset.TableName" />
    	</facet>
    	<facet name="ort" labelKey="Lokalisierung">
	    	<context type="ort" separator=", ">
		    	<field datasource=".Stadt" />
		    	<field datasource=".Land" />
	    	</context>
    	</facet>
    	<facet name="datierung-epoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".AnfEpoche"/>
	    	</context>
    	</facet>
    	<facet name="datierung-epoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".EndEpoche"/>
	    	</context>
    	</facet>
    	<facet name="objektgattung" labelKey="Gattung">
	    	<field datasource="objekt.GattungAllgemein"/>
    	</facet>
    </facets>
</category>
