=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/category.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://arachne.uni-koeln.de/schemas/category"
    targetNamespace="http://arachne.uni-koeln.de/schemas/category"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    <xs:element name="category">        
        <xs:complexType>
            <xs:all>
                <xs:element name="display" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                        	<!-- shouldn't title and subtitle may be only of a single field? -->
                            <xs:element name="title" type="SectionContent" minOccurs="1" maxOccurs="1" />
                            <xs:element name="subtitle" type="SectionContent" minOccurs="1" maxOccurs="1" />
                            <xs:element name="datasections" type="SectionContent" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="facets" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="facet" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="context" type="ContextContent" />
                                        <xs:element name="field" type="FieldContent" />
                                    </xs:choice>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="labelKey" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="hasImage" type="xs:boolean" />
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="SectionContent">
        <xs:choice minOccurs="1" maxOccurs="1">
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="section" type="SectionContent" />
            	<xs:element name="context" type="ContextContent" />
            	<xs:element name="include" type="IncludeContent" />
        	</xs:choice>
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="field" type="FieldContent" />
            	<xs:element name="linkField" type="LinkFieldContent" />
        	</xs:choice>
        </xs:choice>
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="ContextContent">
    	<xs:choice maxOccurs="unbounded">
            <xs:element name="field" type="FieldContent" />
            <xs:element name="linkField" type="LinkFieldContent" />
        </xs:choice>
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="IncludeContent">
    	<xs:attribute name="type" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:complexType name="FieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="field" type="FieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="search" type="xs:string" />
        <xs:attribute name="replace" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="LinkFieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="linkField" type="LinkFieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="labelKey" type="xs:string" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:simpleType name="datasourceString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z\-_]*\.[A-Za-z0-9\-_]+" />
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== BerenikeRe/arachne4/backend/src/test/resources/WEB-INF/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- just very basic to have at least some definitions -->
<category name="test"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
	<display>
		<title>
			<section>
				<field datasource="test.MissingTitle">
					<ifEmpty>
						<field datasource="test.Title" />
					</ifEmpty> 
				</field>
			</section>
		</title>
		<subtitle>
			<section>
				<field datasource="test.SubTitel" />
			</section>
		</subtitle>
		<datasections>
			<section labelKey="Informationen zum Test">
				<section labelKey="Test-Daten">
					<field datasource="test.data1" prefix="Data1: " />
					<field datasource="test.data2" postfix=" of Data2" />
				</section>
			</section>
		</datasections>
	</display>
	<facets>
		<facet name="kategorie" labelKey="Kategorie">
			<field datasource="Dataset.TableName" />
		</facet>
	</facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/einschluss.xml
<?xml version="1.0" encoding="UTF-8"?>
<category name="einschluss" xmlns="http://arachne.uni-koeln.de/schemas/category"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category file:/Users/Patrick/Documents/workspaceSTS/ArachneDataService/src/main/webapp/WEB-INF/xml/category.xsd">
    <display>
        <title>
            <section separator=" / ">
                <field datasource="einschluss.Einschlussart"/>
            </section>
        </title>
        <subtitle>
            <section separator=" / ">
                <field datasource="einschluss.Einschlussart"/>
            </section>
        </subtitle>
        
        <datasections>
            <section labelKey="Informationen zum Einschluss">
                <field datasource="einschluss.Einschlussart"/>
                <field datasource="einschluss.Haeufigkeit"/>
                <field datasource="einschluss.DurchschnittlicheGroesse"/>
                <field datasource="einschluss.Verteilung"/>
                <field datasource="einschluss.Form"/>
                <field datasource="einschluss.Opacity"/>
                <field datasource="einschluss.ColourQualifierVon"/>
                <field datasource="einschluss.ColourFreeVon"/>
                <field datasource="einschluss.ColourQualifierBis"/>
                <field datasource="einschluss.ColourFreeBis"/>
                <field datasource="einschluss.Opacity"/>
            </section>
        </datasections>
    </display>
    <facets>
        <facet name="kategorie" labelKey="Kategorie">
            <field datasource="Dataset.TableName" />
        </facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/sammlungen.xml
<?xml version="1.0" encoding="UTF-8"?>

<category name="sammlungen"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
        	<section separator=" / ">
            	<field datasource="sammlungen.KurzbeschreibungSammlungen" />
            </section>
        </title>
        <subtitle>
             <section separator=" / ">

                    <field datasource="ort.Ort_antik" />

                   	<field datasource="ort.Stadt" />

            </section>
        </subtitle>
        <datasections>
        	<section labelKey="Informationen zum Sammlungen">
        		<section labelKey="Lokalisierung">
	        		<section labelKey="Ort">
	        			<field datasource="sammlungen.OrtSammlungen"/>
	        		</section>
	        		<section labelKey="Land">
	        			<field datasource="sammlungen.LandSammlungen" />
	        		</section>
	        		<context type="ort" separator=", ">
        				<field datasource=".Stadt"  />
        				<field datasource=".Land" />
        				<field datasource=".Countrycode" />
        				<field datasource=".Aufbewahrungsort" />
        			</context>
	        		<section labelKey="Aufstellung">
	        			<field datasource="sammlungen.AufstellungSammlungen" />
	        		</section>
	        	</section>
	        		        	
	        	
	        	<section labelKey="Sammlungskategorie"  separator="; ">
	        		<field datasource="sammlungen.Sammlungskategorie"/>
	        	</section>
	        	
	            <section labelKey="Geschichte"  separator="; ">
	            	<section labelKey="Entstehung">
	        			<field datasource="sammlungen.Entstehung" />
	        		</section>
	            
	        		<section labelKey="Sammlung">
	        			<field datasource="sammlungen.GeschichteSammlungen" />
	        		</section>
	        		<section labelKey="Auflösung">
	        			<field datasource="sammlungen.AufloesungDatum" />
	        			<field datasource="sammlungen.Aufloesung" />
	        			<field datasource="sammlungen.AufloesungArt" />
	        		</section>
	        	</section>
	        	
	        	<!-- 
	        	TODO Sammler und Personen müssen eingepflegt werden
	        	 -->
	        	
	        	<section labelKey="Quellen"  separator="; ">
	        		<field datasource="sammlungen.Quellen" />
	        	</section>
	        	
	        	<context type="literatur" labelKey="Literatur" separator=" ">
	            	<field datasource=".DAIRichtlinien" />
	            	<field datasource=".Seite" />
	            </context>

	    	</section>
        </datasections>
    </display>
    <facets>
    <!-- 
    	TODO Revise!
     -->
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="arachneentityidentification.TableName" />
    	</facet>
    	<facet name="ort" labelKey="Lokalisierung">
	    	<context type="ort" separator=", ">
		    	<field datasource=".Stadt" />
		    	<field datasource=".Land" />
	    	</context>
    	</facet>
    	<facet name="datierung-epoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".AnfEpoche"/>
	    	</context>
    	</facet>
    	<facet name="datierung-epoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".EndEpoche"/>
	    	</context>
    	</facet>
    	<facet name="Sammlungskategorie" labelKey="Sammlungskategorie">
	    	<field datasource="sammlungen.Sammlungskategorie"/>
    	</facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/person.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- just very basic to have at least some definitions -->
<category name="person"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
        	<section separator=", ">
        		<field datasource="person.FamVatersnameSonst" />
        		<field datasource="person.Namenszusatz" />
        	</section>	
        </title>
        <subtitle>
        	<section separator=", ">
            	<field datasource="person.VornameSonst" />
            	<field datasource="person.Cognomen" />
            	<field datasource="person.Beiname" />	
            </section>
        </subtitle>
        <datasections>
        	<section labelKey="Informationen zur Person">
        		<section labelKey="Informationen zum Namen ">
        			<section labelKey="Namenssynonyme" separator="; ">
        				<field datasource="person.VornameSonstSynonym1" />
            			<field datasource="person.VornameSonstSynonym2" />
            			<field datasource="person.VornameSonstSynonym3" />
            			<field datasource="person.VornameSonstSynonym4" />
        			</section>
        			<section labelKey="Synonyme Vatersname" separator="; "> 
        	 			<field datasource="person.FamVatersnameSonstSynonym1" />
        				<field datasource="person.FamVatersnameSonstSynonym2" />
        	 			<field datasource="person.FamVatersnameSonstSynonym3" />
        	 			<field datasource="person.FamVatersnameSonstSynonym4" />
        		</section>
        		<section labelKey="Synonyme Cognomen" separator="; ">
        			<field datasource="person.CognomenSynonym1" />
        			<field datasource="person.CognomenSynonym2" />
        			<field datasource="person.CognomenSynonym3" />
        			<field datasource="person.CognomenSynonym4" />
        		</section>
        	</section>
        		<section labelKey="Beschreibung">
	            	<field datasource="person.Kurzbeschreibung" />
	            </section>
	            <section labelKey="Titel">
	            	<field datasource="person.Titel" />
	            </section>
	            <section labelKey="Geschlecht">
	            	<field datasource="person.Geschlecht" />
	            </section>
	            <section labelKey="NationalitÃ¤t">
	            	<field datasource="person.EthnieNationalitaet" />
	            </section>
        	</section>
        </datasections>
    </display>
    <facets>
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="Dataset.TableName" />
    	</facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/isolatedsherd.xml
<?xml version="1.0" encoding="UTF-8"?>
<category name="isolatedsherd" xmlns="http://arachne.uni-koeln.de/schemas/category"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
            <section separator=" / ">
                <field datasource="isolatedsherd.InventoryNumber"/>
                <field datasource="isolatedsherd.NitonAnalysisID"/>
            </section>
        </title>
        <subtitle>
            <section separator=" / ">
                <field datasource="isolatedsherd.SherdType"/>
            </section>
        </subtitle>
        
        <datasections>
            <section labelKey="Informationen zum Keramikfragment">
                <field datasource="isolatedsherd.SherdType"/>
                <field datasource="isolatedsherd.Diameter" postfix="cm"/>
                <field datasource="isolatedsherd.Height" postfix="cm"/>
                <field datasource="isolatedsherd.Width" postfix="cm"/>
                <field datasource="isolatedsherd.Length" postfix="cm"/>
                <field datasource="isolatedsherd.Thickness" postfix="cm"/>
                <field datasource="isolatedsherd.Weight" postfix="g"/>
                <field datasource="isolatedsherd.RimPercentage" postfix="%"/>
            </section>
            <section labelKey="Informationen zur Oberflaechenbehandlung">
                <context type="surfacetreatment" labelKey="OberflÃ¤chenbehandlung" separator=" ">
                    <field datasource=".Bezeichner"/>
                    <field datasource=".ConnectedActions"></field>
              </context>
            </section>
            <include type="ort" />
        </datasections>
    </display>
    <facets>
        <facet name="kategorie" labelKey="Kategorie">
            <field datasource="Dataset.TableName" />
        </facet>
    </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/morphology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  CeramEgypt Objects 2.0
  This represents a type of morphology
  status: to be done
-->
<category xmlns="http://arachne.uni-koeln.de/schemas/category" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="morphology" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
  <display>
    <title>
      <section separator=", " labelKey="Morphology">
        <!-- field datasource="morphology.Level1"/ -->
        <field datasource="morphology.Level2"/>
        <field datasource="morphology.Level3"/>
        <field datasource="morphology.Level4"/>
        <field datasource="morphology.Level5"/>
        <field datasource="morphology.Level6"/>
      </section>
    </title>
    <subtitle>
      <section labelKey="Unique Identifier">
        <field datasource="Dataset.Id"/>
      </section>
    </subtitle>
    <datasections>

        <include type="morphology"></include>

        <include type="datierung"/>

        <context type="Entitymainabstractisolatedsherd" labelKey="Fragment">
          <contextSection labelKey="Typ">
            <field datasource=".SherdType"/>
          </contextSection>
          <contextSection labelKey="Inventarnummer">
            <field datasource=".InventoryNumber"/>
          </contextSection>
          <contextSection labelKey="Niton-Analyse-Nummer">
            <field datasource=".NitonAnalysisNumber"/>
          </contextSection>
        </context>

    </datasections>
    <contextImages>
      <!-- Show images of all isolated sherds which are conntected with the current morphology -->
      <contextImage show="always">Entitymainabstractisolatedsherd</contextImage>
    </contextImages>
  </display>

  <facets>
    <include type="facet_kategorie"/>
	<facet name="morphology_functionalgroup" labelKey="Funktionelle Gruppe">
    	<field datasource="morphology.Level1"/>
    </facet>
    <facet name="morphology_2ndLevel" labelKey="2nd Level"><!-- yes, it's intentional, that level 2 does not depends on 1 -->
    	<field datasource="morphology.Level2"/>
    </facet>    
    <facet name="morphology_3thLevel" labelKey="3rd Level" dependsOn="morphology_2ndLevel">
		<field datasource="morphology.Level3"/>
    </facet>    
    <facet name="morphology_4thLevel" labelKey="4th Level" dependsOn="morphology_3thLevel">
		<field datasource="morphology.Level4"/>
    </facet>    
    <facet name="morphology_5thLevel" labelKey="5th Level" dependsOn="morphology_4thLevel">
		<field datasource="morphology.Level5"/>
    </facet>
    <include type="facet_datierung" />
    <facet name="grabungsinternetypnummer" labelKey="Grabungsinterne Typnummer">
      <context type="mainabstract" separator="">
        <field datasource=".GrabungsinterneTypennummer"/>
        <field datasource=".GrabungsinterneTypennummerSub"/>
      </context>
    </facet>
  </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/niton.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- just very basic to have at least some definitions -->
<category xmlns="http://arachne.uni-koeln.de/schemas/category" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="niton" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
  <display>
    <title>
      <section>
        <field datasource="niton.Sample"/>
      </section>
    </title>
    <subtitle>
      <section>
        <field datasource="niton.Location"/>
      </section>
    </subtitle>
    <datasections>
      <section labelKey="Informationen">
        <section labelKey="Zeit">
          <field datasource="niton.Time"/>
        </section>
      </section>
    </datasections>
  </display>
  <facets>
    <include type="facet_kategorie"/>
  </facets>
</category>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/typus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 

TODO
Hier werden keine Direkten Bilder verwendet sondern die Bilder des Hauptvertreters. Dies muss entweder im an anderer Stelle im Code berücksichtigt werden ODER Hier das ist aber nochnicht möglich!

 -->
<category name="typus"
	xmlns="http://arachne.uni-koeln.de/schemas/category"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/category category.xsd">
    <display>
        <title>
        	<section>
            	<field datasource="typus.KurzbeschreibungTypus" />
            </section>
        </title>
        <subtitle>
             <section>
                          
				<!-- 
				Strange Has no Subtitle , 
				this is Something is something taken from the Data 
				-->
                    <field datasource="typus.moderneLandschaft"/>


            </section>
        </subtitle>
        <datasections>
        	<section labelKey="Informationen zum Typus">
        	            <section labelKey="Allgemein">
	            	<section labelKey="Typus-Hauptbezeichnung" separator=", ">
	                    <field datasource="typus.KurzbeschreibungTypus" />
	                </section>  
	                <section labelKey="Typus-Nebenbezeichnung(en)">
	                	<field datasource="typus.TypusNebenbezeichnung" />
	                </section>
	                <section labelKey="">
	                	<field datasource="typus.RoemGriech" />
	                </section>
	                <section labelKey="Klassifizierung">
	                	<field datasource="typus.Klassifizierung" />
	                </section>
	                <section labelKey="moderne Landschaft">
	                    <field datasource="typus.moderneLandschaft" />
	                </section>
	                <section labelKey="Ausdehnung">
	                    <field datasource="typus.Ausdehnung" />
	                </section>
	                <section labelKey="Bildschema">
	                    <field datasource="typus.Bildschema" />
	                </section>
	                <section labelKey="Namensgebende Replik / Hauptvertreter">
	                    <field datasource="typus.NamengebendeReplik" />
	                </section>
	                <section labelKey="Künstler">
	                    <field datasource="typus.KuenstlerTypus" />
	                </section>
	            </section>
	            
	            <section labelKey="Quellen">
	                    <field datasource="typus.AntikeQuelle" />
	            </section>
	            <section labelKey="Beschreibung" separator="; ">
	            	<section labelKey="Haltung">
	                    <field datasource="typus.HaltungTypus" />
	                </section>  
	                <section labelKey="Attribute">
	                	<field datasource="typus.AttributTypus" />
	                </section>
	                <section labelKey="Bekleidung">
	                	<field datasource="typus.BekleidungTypus" />
	                </section>
	                <section labelKey="Haar">
	                	<field datasource="typus.Haartracht" />
	                </section>
	                <section labelKey="Kopfwendung">
	                    <field datasource="typus.KopfwendungTypus" />
	                </section>
	                <section labelKey="Bart">
	                    <field datasource="typus.Bartrracht" />
	                </section>
	                <section labelKey="Stirnhaar">
	                    <field datasource="typus.StirnhaarTypus" />
	                </section>
	            </section>
	            <section labelKey="Merkmale" separator="; ">
	            	<section labelKey="">
	                    <field datasource="typus.KunsthistorischeEinordnung" />
	                </section>  
	                <section labelKey="Kommentar">
	                	<field datasource="typus.HistorischerKommentar" />
	                </section>
	                <section labelKey="">
	                	<field datasource="typus.Bemerkung" />
	                </section>
	        
	            </section>
	            
	            <section labelKey="Einordnung">      
	            	<field datasource="typus.Einordnungsargumente" />
	            </section>
	            
	            
	            <section labelKey="Vorbild/Kopie" separator="; " >
	            	<section labelKey="Kommentar Vorbild">
	                    <field datasource="typus.KommentarVorbild" />
	                </section>  
	                <section labelKey="Kommentar Kopien/Varianten/Vergleiche">
	                	<field datasource="typus.KommentarKopien" />
	                </section>
	            </section>
	            <section labelKey="Datierung">
	            	<context type="datierung" labelKey="Typus" separator=" ">
	            		<field datasource=".AnfEpoche" postfix="," />
	            		<field datasource=".AnfDatZeitraum" />
	            		<field datasource=".AnfDatJh" postfix=". Jh."/>
	            		<field datasource=".AnfDatvn" />
	            	</context>
	            </section>
	            
	            
	            <context type="literatur" labelKey="Literatur" separator=" ">
	            	<field datasource=".DAIRichtlinien" />
	            	<field datasource=".Seite" />
	            </context>
	    	</section>
        </datasections>
    </display>
    <facets>
    	<facet name="kategorie" labelKey="Kategorie">
    		<field datasource="Dataset.TableName" />
    	</facet>
    	<!-- 
    	<facet name="ort" labelKey="Lokalisierung">
	    	<context type="ort" separator=", ">
		    	<field datasource=".Stadt" />
		    	<field datasource=".Land" />
	    	</context>
    	</facet>
    	 -->
    	<facet name="datierung-epoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".AnfEpoche"/>
	    	</context>
    	</facet>
    	<facet name="datierung-epoche" labelKey="Epoche">
	    	<context type="datierung">
		    	<field datasource=".EndEpoche"/>
	    	</context>
    	</facet>
    	<facet name="klassifizierung" labelKey="Art des Typus">
	    	<field datasource="typus.Klassifizierung"/>
    	</facet>
    </facets>
</category>
