=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/include.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://arachne.uni-koeln.de/schemas/include"
    targetNamespace="http://arachne.uni-koeln.de/schemas/include"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    <xs:element name="includeSection">        
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="1">
            	<xs:element name="section" type="SectionContent" />
            	<xs:element name="context" type="ContextContent" />
        	</xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="SectionContent">
        <xs:choice minOccurs="1" maxOccurs="1">
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="section" type="SectionContent" />
            	<xs:element name="context" type="ContextContent" />
        	</xs:choice>
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="field" type="FieldContent" />
            	<xs:element name="linkField" type="LinkFieldContent" />
        	</xs:choice>
        </xs:choice>
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="ContextContent">
    	<xs:choice maxOccurs="unbounded">
            <xs:element name="field" type="FieldContent" />
            <xs:element name="linkField" type="LinkFieldContent" />
        </xs:choice>
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
        
    <xs:complexType name="FieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="field" type="FieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="search" type="xs:string" />
        <xs:attribute name="replace" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="LinkFieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="linkField" type="LinkFieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="labelKey" type="xs:string" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:simpleType name="datasourceString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z\-_]*\.[A-Za-z0-9\-_]+" />
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/isolatedsherd_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">
  <!-- Direkte Informationen ueber die gespeicherte Scherbe -->
  <section>
    <section labelKey="Inventarnummer">
      <field datasource="isolatedsherd.InventoryNumber"/>
    </section>
    <section labelKey="Typus">
      <field datasource="isolatedsherd.SherdType" postfix="--" prefix="--" />
    </section>
    <section labelKey="Durchmesser">
      <field datasource="isolatedsherd.Diameter" postfix="cm"/>
    </section>
    <section labelKey="Höhe">
      <field datasource="isolatedsherd.Height" postfix="cm"/>
    </section>
    <section labelKey="Breite">
      <field datasource="isolatedsherd.Width" postfix="cm"/>
    </section>
    <section labelKey="Länge">
      <field datasource="isolatedsherd.LengthSize" postfix="cm"/>
    </section>
    <section labelKey="Dicke">
      <field datasource="isolatedsherd.Thickness" postfix="cm"/>
    </section>
    <section labelKey="Gewicht">
      <field datasource="isolatedsherd.Weight" postfix="g"/>
    </section>
    <section labelKey="Prozentualer Randanteil">
      <field datasource="isolatedsherd.RimPercentage" postfix="%"/>
    </section>
  </section>



</includeSection>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/literatur_arachne_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">
	<context type="buch" labelKey="Literatur in Arachne" link="">
		<field datasource=".contextUri" prefix="$link$" />
		<field datasource=".BuchTitel">
			<ifEmpty>
				<field datasource="zenon.245_a">
					<ifEmpty>
						<field datasource=".KurzbeschreibungBuch" />
					</ifEmpty>
				</field>
			</ifEmpty>
		</field>
	</context>
</includeSection>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/fabric_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  CeramEgypt Objects 2.0
  a type of fabric
-->
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">

    <section>
        <section labelKey="Name">
            <field datasource="fabric.Name"/>
        </section>

        <section labelKey="AllgemeinerName">
            <field datasource="fabric.CommonName"/>
        </section>

        <section labelKey="Kommentare">
            <field datasource="fabric.Comments"/>
        </section>

        <section labelKey="Herkunft">
            <field datasource="fabric.Origin"/>
        </section>

        <section labelKey="Machart">
            <field datasource="fabricdescription.Manufacture"/>
        </section>

        <section labelKey="Härte">
            <field datasource="fabricdescription.Hardness"/>
        </section>

        <section labelKey="Porösität">
            <field datasource="fabricdescription.Porosity"/>
        </section>

        <section labelKey="Zoning">
            <field datasource="fabricdescription.Zoning"/>
        </section>

        <section labelKey="Oberflächengefühl">
            <field datasource="fabricdescription.SurfaceFeel"/>
        </section>

        <section labelKey="Freie Farbbeschreibung" separator=" ">
            <field datasource="fabricdescription.ColourQualifierFreeVon"/>
            <field datasource="fabricdescription.ColourFreeVon" postfix=" -"/>
            <field datasource="fabricdescription.ColourQualifierFreeBis"/>
            <field datasource="fabricdescription.ColourFreeBis"/>
        </section>
        <section labelKey="Farbe der Bruchstelle" separator=" ">
            <field datasource="fabricdescription.ColourOfBreakQualifierVon"/>
            <field datasource="fabricdescription.ColourOfBreakVon" postfix=" -"/>
            <field datasource="fabricdescription.ColourOfBreakQualifierBis"/>
            <field datasource="fabricdescription.ColourOfBreakBis"/>
        </section>
        <section labelKey="Farbe des Kerns" separator=" ">
            <field datasource="fabricdescription.ColourOfCoreQualifierVon"/>
            <field datasource="fabricdescription.ColourOfCoreVon" postfix=" - "/>
            <field datasource="fabricdescription.ColourOfCoreQualifierBis"/>
            <field datasource="fabricdescription.ColourOfCoreBis"/>
        </section>
        <section labelKey="Farbe der Oberfläche" separator=" ">
            <field datasource="fabricdescription.ColourOfOutsideQualifierVon"/>
            <field datasource="fabricdescription.ColourOfOutsideVon" postfix=" -"/>
            <field datasource="fabricdescription.ColourOfOutsideQualifierBis"/>
            <field datasource="fabricdescription.ColourOfOutsideBis"/>
        </section>

    </section>

</includeSection>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/morphology_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  CeramEgypt Objects 2.0
  a morphology
-->
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">

    <section>

        <section labelKey="Functional Group">
            <field datasource="morphology.Level1"/>
        </section>

        <section separator=", " labelKey="Morphologiedetails">
            <field datasource="morphology.Level2"/>
            <field datasource="morphology.Level3"/>
            <field datasource="morphology.Level4"/>
            <field datasource="morphology.Level5"/>
            <field datasource="morphology.Level6"/>
        </section>

        <section labelKey="Interne Typnummer" separator=", ">
            <field datasource="mainabstract.GrabungsinterneTypennummer"/>
            <field datasource="mainabstract.GrabungsinterneTypennummerSub"/>
        </section>

    </section>

</includeSection>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/quantities_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  CeramEgypt Objects 2.0
  a quantified set of ceramic objects
-->
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">

    <section labelKey="Weitere Quantifierzungsinformationen">
        <section labelKey="Randanteil">
            <field datasource="quantities.RimPercentage" postfix="%"/>
        </section>
        <section labelKey="Anzahl Joins">
            <field datasource="quantities.Joins"/>
        </section>
        <section labelKey="MNI">
            <field datasource="quantities.MNI"/>
        </section>
        <section labelKey="Gewichtetes MNI">
            <field datasource="quantities.MNIWeighted"/>
        </section>
        <section labelKey="MXI">
            <field datasource="quantities.MXI"/>
        </section>
    </section>

    <section labelKey="Gewicht">
        <section labelKey="Ränder">
            <field datasource="quantities.RimWeight" postfix="g"/>
        </section>
        <section labelKey="Henkel">
            <field datasource="quantities.HandleWeight" postfix="g"/>
        </section>
        <section labelKey="Bodenfragmente">
            <field datasource="quantities.BaseWeight" postfix="g"/>
        </section>
        <section labelKey="Wandscherben">
            <field datasource="quantities.BodySherdWeight" postfix="g"/>
        </section>
        <section labelKey="Weitere Fragmente">
            <field datasource="quantities.OthersWeight" postfix="g"/>
        </section>
    </section>

    <section labelKey="Anzahl">
        <section labelKey="Ränder">
            <field datasource="quantities.RimCount"/>
        </section>
        <section labelKey="Henkel">
            <field datasource="quantities.HandleCount"/>
        </section>
        <section labelKey="Bodenfragmente">
            <field datasource="quantities.BaseCount"/>
        </section>
        <section labelKey="Wandscherben">
            <field datasource="quantities.BodySherdCount"/>
        </section>
        <section labelKey="Weitere Fragmente">
            <field datasource="quantities.OthersCount"/>
        </section>
        <section labelKey="Gesamt">
            <field datasource="quantities.TotalSherds"/>
        </section>
    </section>

</includeSection>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/einschluss_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  CeramEgypt Objects 2.0
  a type of fabric
-->
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">

    <section>

        <section labelKey="Einschlussart">
            <field datasource="einschluss.Einschlussart" />
        </section>

        <section labelKey="Häufigkeit">
            <field datasource="einschluss.Haeufigkeit" />
        </section>

        <section labelKey="Durchschnittliche Größe">
            <field datasource="einschluss.DurchschnittlicheGroesse" />
        </section>

        <section labelKey="Verteilung">
            <field datasource="einschluss.Verteilung" />
        </section>

        <section labelKey="Form">
            <field datasource="einschluss.Form" />
        </section>

        <section labelKey="Deckkraft">
            <field datasource="einschluss.Opacity" />
        </section>

        <section labelKey="Freie Farbbeschreibung" separator=" ">
            <field datasource="einschluss.ColourQualifierFreeVon"/>
            <field datasource="einschluss.ColourFreeVon" postfix=" -"/>
            <field datasource="einschluss.ColourQualifierFreeBis"/>
            <field datasource="einschluss.ColourFreeBis"/>
        </section>

    </section>



</includeSection>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/surface_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  CeramEgypt Objects 2.0
  description of special treatments to the surface

  <context type="surface" labelKey="Surface Treatments">
        <contextSection>
            <subtitle separator="|||">
              <field prefix="Treatment: " datasource=".surfacetreatment.Bezeichner" />
              <field prefix="Puff: " datasource="surfacetreatment.Bezeichner" />
            </subtitle>
            <field prefix="STID:" datasource=".surfacetreatment.PS_surfaceTreatmentID" />
            <field prefix="STDG:" datasource=".surfacetreatment.DatensatzGruppeSurfacetreatment" />
            <subcontext type="surfacetreatmentaction">
              <field prefix="Action: " datasource=".TreatmentAction" />
              <field prefix="Position: " datasource=".TreatmentPosition" />
              <field prefix="FreeDescription: " datasource=".FreeDescription" />
            </subcontext>
        </contextSection>
      </context>

-->
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">

    <context type="surface" labelKey="Oberflächenbehandlungen">
        <contextSection>
            <subtitle>
                <field datasource="surfacetreatment.Bezeichner" />
            </subtitle>

            <subcontext type="surfacetreatmentaction">

                <field prefix="[" postfix="]" datasource=".TreatmentAction"/>

                <field prefix="Spezielle Überzugstechnik: " datasource=".TreatmentActionSubCoating" />
                <field prefix="Beschreibung der Einkerbung: " datasource=".IncisionDescription" />
                <field prefix="Stempel: " datasource=".StampedStamp" />
                <field prefix="Art des hinzugefügten Materials: " datasource=".AddedMaterialType" />

                <field prefix="Zeitpunkt der Oberflächenbehandlung: " datasource=".MomentOfSurfaceTreatmentAction" />
                <field prefix="Position der Oberflächenbehandlung: " datasource=".TreatmentPosition" />
                <field prefix="Behandelter Teil der Oberfläche: " datasource=".PartOfSurfaceTreated" />
                <field prefix="Zustand: " datasource=".Condition" />
                <field prefix="Anzahl vorhandener Fragmente mit dieser Oberflächenbehandlung: " datasource=".NumberOfSherds" />

                <field prefix="Dicke: " datasource=".Thickness" />
                <field prefix="Glanz: " datasource=".Glossiness" />
                <field prefix="Erhaltung: " datasource=".Conservation" />
                <field prefix="Qualität: " datasource=".Quality" />
                <field prefix="Homogenität: " datasource=".Homogenity" />
                <field prefix="Anhaftung: " datasource=".Adherence" />
                <field prefix="Ausrichtung: " datasource=".Alignment" />
                <field prefix="Freie Beschreibung: " datasource=".FreeDescription" />
            </subcontext>
        </contextSection>
    </context>

</includeSection>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/facet_personrole_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<includeSection
	xmlns="http://arachne.uni-koeln.de/schemas/include"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">
	<facet name="personroleauthor" labelKey="Autor" group="person">
		<context type="personroleauthor" separator="">
			<field datasource=".Namenszusatz" postfix=" " />
			<field datasource=".FamVatersnameSonst" />
			<field datasource=".VornameSonst" prefix=", " />
		</context>
	</facet>
	<facet name="personroleaddressee" labelKey="Adressat"
		group="person">
		<context type="personroleaddressee" separator="">
			<field datasource=".Namenszusatz" postfix=" " />
			<field datasource=".FamVatersnameSonst" />
			<field datasource=".VornameSonst" prefix=", " />
		</context>
	</facet>
	<facet name="personroletopic" labelKey="Behandelt" group="person">
		<context type="personroletopic" separator="">
			<field datasource=".Namenszusatz" postfix=" " />
			<field datasource=".FamVatersnameSonst" />
			<field datasource=".VornameSonst" prefix=", " />
		</context>
	</facet>
	<facet name="personrolenone" labelKey="Ohne Rolle" group="person">
		<context type="personrolenone" separator="">
			<field datasource=".Namenszusatz" postfix=" " />
			<field datasource=".FamVatersnameSonst" />
			<field datasource=".VornameSonst" prefix=", " />
		</context>
	</facet>
</includeSection>
