=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/include.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://arachne.uni-koeln.de/schemas/include"
    targetNamespace="http://arachne.uni-koeln.de/schemas/include"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    <xs:element name="includeSection">        
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="1">
            	<xs:element name="section" type="SectionContent" />
            	<xs:element name="context" type="ContextContent" />
        	</xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="SectionContent">
        <xs:choice minOccurs="1" maxOccurs="1">
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="section" type="SectionContent" />
            	<xs:element name="context" type="ContextContent" />
        	</xs:choice>
        	<xs:choice maxOccurs="unbounded">
            	<xs:element name="field" type="FieldContent" />
            	<xs:element name="linkField" type="LinkFieldContent" />
        	</xs:choice>
        </xs:choice>
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="ContextContent">
    	<xs:choice maxOccurs="unbounded">
            <xs:element name="field" type="FieldContent" />
            <xs:element name="linkField" type="LinkFieldContent" />
        </xs:choice>
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="labelKey" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
        
    <xs:complexType name="FieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="field" type="FieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="search" type="xs:string" />
        <xs:attribute name="replace" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="LinkFieldContent">
        <xs:all minOccurs="0">
            <xs:element name="ifEmpty">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="linkField" type="LinkFieldContent"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="datasource" type="datasourceString" use="required"/>
        <xs:attribute name="labelKey" type="xs:string" use="required"/>
        <xs:attribute name="prefix" type="xs:string" />
        <xs:attribute name="postfix" type="xs:string" />
        <xs:attribute name="separator" type="xs:string" />
        <xs:attribute name="minGroupId" type="xs:string" />
    </xs:complexType>
    
    <xs:simpleType name="datasourceString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z\-_]*\.[A-Za-z0-9\-_]+" />
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/befund_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  CeramEgypt Objects 2.0
  localisation of finding
-->
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">

    <section>
        <section labelKey="Grabungsort">
            <field datasource="befund.Grabungsort"/>
        </section>
        <section labelKey="Areal">
            <field datasource="befund.Areal"/>
        </section>
        <section labelKey="Befund">
            <field datasource="befund.Befund"/>
        </section>
        <section labelKey="Abhub">
            <field datasource="befund.Abhub"/>
        </section>
        <section labelKey="Kommentar">
            <field datasource="befund.Kommentar"/>
        </section>
    </section>

</includeSection>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/literaturcomplete_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">
  <context type="literaturcomplete" labelKey="Literatur" separator=", ">
    <field datasource=".arachneLinkStart" separator="" />
	<field datasource=".tempLiteratur" />
	<field datasource=".Abkuerzungen">
		<ifEmpty>
			<field datasource=".DAIRichtlinien" />
		</ifEmpty>
	</field>
	<field datasource=".Corpuszitat" />
	<field datasource=".AntikeTextquelle" />
	<field datasource=".Seite" />
	<field datasource=".Anmerkung" prefix="Anm. " />
	<!-- AdditionalInfosJSON -->
	<field datasource=".Abbildung" prefix="Abb. " />
	<!-- AdditionalInfosJSON -->
    <field datasource=".Katnummer" prefix="Kat.Nr. " />
    <!-- AdditionalInfosJSON -->
    <field datasource=".Tafel" prefix="Taf. " />
    <!-- AdditionalInfosJSON -->
    <field datasource=".Figur" prefix="Fig. " />
    <!-- AdditionalInfosJSON -->
    <field datasource=".Beilage" prefix="Beil. " />
    <!-- AdditionalInfosJSON -->
    <field datasource=".subVoce" prefix="s.v. " />
    <!-- AdditionalInfosJSON -->
    <field datasource=".Textauszug" prefix="[Textauszug: '" postfix="']" />
    <!-- AdditionalInfosJSON -->
    <field datasource=".TextauszugUebersetzung" prefix="[Übersetzter Textauszug: '" postfix="']" />
    <!-- AdditionalInfosJSON -->
    <field datasource=".KommentarLitZitat" prefix="(" postfix=")" />
    <field datasource=".Supplement" prefix="Supplement: " />
    <!-- AdditionalInfosJSON -->
    <field datasource=".arachneLinkEnd" overrideSeparator="" separator=" " />
    <linkField labelKey="Online verfügbar" datasource=".Onlinequelle" overrideSeparator=" "/>
    <linkField labelKey="Zenon" datasource=".ZenonID" prefix="https://zenon.dainst.org/Record/" overrideSeparator=" " />
  </context>
</includeSection>

=== BerenikeRe/arachne4/backend/src/main/webapp/WEB-INF/xml/personsammlungcomplete_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<includeSection xmlns="http://arachne.uni-koeln.de/schemas/include" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arachne.uni-koeln.de/schemas/include include.xsd">
    <context type="personcomplete" labelKey="Personen und Sammler" separator=" ">
        <field datasource=".arachneLinkStart" separator="" />
        <field datasource=".Sammlerreihenfolge" postfix=".)"/>
        <field datasource=".Titel"/>
        <field datasource=".VornameSonst"/>
        <field datasource=".Namenszusatz"/>
        <field datasource=".FamVatersnameSonst"/>
        <field datasource=".Cognomen"/>
        <field datasource=".Kurzbeschreibung" prefix=" - "/>
        <field datasource=".Verwandtschaftsverhaeltnis" prefix=" - "/>
        <field datasource=".arachneLinkEnd" overrideSeparator="" separator=" " />
    </context>
</includeSection>
